{{- if .Values.networkPolicy.enabled }}
# Default Deny All Network Policy (Security Baseline)
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "app.fullname" . }}-deny-all
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  - Egress

---
# Allow Ingress Traffic to App
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "app.fullname" . }}-allow-ingress
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "app.selectorLabels" . | nindent 6 }}
  policyTypes:
  - Ingress
  ingress:
  # Allow traffic from ingress controller
  - from:
    - namespaceSelector:
        matchLabels:
          name: {{ .Values.networkPolicy.ingressControllerNamespace | default "ingress-nginx" }}
    - podSelector:
        matchLabels:
          app.kubernetes.io/name: ingress-nginx
    ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
  {{- if .Values.networkPolicy.allowFromSameNamespace }}
  # Allow traffic from same namespace (for service-to-service communication)
  - from:
    - podSelector: {}
    ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
  {{- end }}
{{- end }}